### ISSUE TITLE
BTDEX Cache directory should, by default, point to UnRAID's cache directory

### ISSUE THREAD

**Issue by furritos** [paulpoco/docker-templates#4]
Reviewing this piece of item in the XML:

![image](https://user-images.githubusercontent.com/2133717/156109489-9fc3b4bd-11c0-490a-9e83-cc9f202bc6fe.png)

It would be beneficial and within UnRAID's wheelhouse to set this default directory to UnRAID's cache directory.  The UnRAID system administrator can then override this value to their needs.

**Comment by paulpoco** [comment]
The appdata directory is on the cache drive already

**Comment by paulpoco** [comment]
The correct format is always /mnt/user/appdata and not /mnt/cache/appdata because appdata share is always on the cache drive.
