### ISSUE TITLE
Unknown Category error in BTDEX callout page

### ISSUE THREAD

**Issue by furritos** [paulpoco/docker-templates#6]
There is a "unknown category" error showing up in the callout page:

![image](https://user-images.githubusercontent.com/2133717/156110132-e0525279-9435-4ce4-8e51-536f72c97db5.png)

**Comment by furritos** [comment]
Validation pending UnRAID app refresh.

**Comment by paulpoco** [comment]
Changed Category to just Crypto: per Squid
